// Enhanced Authentication with JWT-style token management
import { User } from './auth'

const TOKEN_STORAGE_KEY = 'clinic_auth_token'
const USER_STORAGE_KEY = 'clinic_current_user'
const TOKEN_EXPIRY_KEY = 'clinic_token_expiry'

export interface AuthToken {
  token: string
  expiresAt: number
  issuedAt: number
  userId: string
  role: string
}

export interface SessionInfo {
  user: User
  token: AuthToken
  isValid: boolean
}

/**
 * Generate a simple JWT-style token (client-side only)
 * In production, this should be generated by the backend
 */
export function generateToken(user: User): AuthToken {
  const now = Date.now()
  const expiresIn = 8 * 60 * 60 * 1000 // 8 hours in milliseconds
  
  // Create a simple token (in production, use proper JWT signing)
  const tokenData = {
    userId: user.id,
    username: user.username,
    role: user.role,
    iat: now,
    exp: now + expiresIn
  }
  
  // Base64 encode the token data (in production, use JWT library)
  const token = btoa(JSON.stringify(tokenData))
  
  return {
    token,
    expiresAt: now + expiresIn,
    issuedAt: now,
    userId: user.id,
    role: user.role
  }
}

/**
 * Validate and decode token
 */
export function validateToken(token: string): { valid: boolean; decoded?: any; reason?: string } {
  try {
    // Decode the token
    const decoded = JSON.parse(atob(token))
    
    // Check expiration
    const now = Date.now()
    if (decoded.exp < now) {
      return { valid: false, reason: 'Token expired' }
    }
    
    // Check if token was issued in the future (clock skew)
    if (decoded.iat > now + 60000) { // Allow 1 minute clock skew
      return { valid: false, reason: 'Invalid token timestamp' }
    }
    
    return { valid: true, decoded }
  } catch (error) {
    return { valid: false, reason: 'Invalid token format' }
  }
}

/**
 * Store authentication session
 */
export function storeSession(user: User, token: AuthToken): void {
  try {
    localStorage.setItem(USER_STORAGE_KEY, JSON.stringify(user))
    localStorage.setItem(TOKEN_STORAGE_KEY, token.token)
    localStorage.setItem(TOKEN_EXPIRY_KEY, token.expiresAt.toString())
  } catch (error) {
    console.error('Failed to store session:', error)
  }
}

/**
 * Get current session
 */
export function getSession(): SessionInfo | null {
  try {
    const userStr = localStorage.getItem(USER_STORAGE_KEY)
    const token = localStorage.getItem(TOKEN_STORAGE_KEY)
    const expiryStr = localStorage.getItem(TOKEN_EXPIRY_KEY)
    
    if (!userStr || !token || !expiryStr) {
      return null
    }
    
    const user: User = JSON.parse(userStr)
    const expiresAt = parseInt(expiryStr, 10)
    const now = Date.now()
    
    // Check if token is expired
    if (expiresAt < now) {
      clearSession()
      return null
    }
    
    // Validate token
    const validation = validateToken(token)
    if (!validation.valid) {
      clearSession()
      return null
    }
    
    return {
      user,
      token: {
        token,
        expiresAt,
        issuedAt: validation.decoded.iat,
        userId: user.id,
        role: user.role
      },
      isValid: true
    }
  } catch (error) {
    console.error('Failed to get session:', error)
    return null
  }
}

/**
 * Clear session (logout)
 */
export function clearSession(): void {
  try {
    localStorage.removeItem(USER_STORAGE_KEY)
    localStorage.removeItem(TOKEN_STORAGE_KEY)
    localStorage.removeItem(TOKEN_EXPIRY_KEY)
  } catch (error) {
    console.error('Failed to clear session:', error)
  }
}

/**
 * Check if session is valid
 */
export function isSessionValid(): boolean {
  const session = getSession()
  return session !== null && session.isValid
}

/**
 * Get current user
 */
export function getCurrentUser(): User | null {
  const session = getSession()
  return session?.user || null
}

/**
 * Get token for API requests
 */
export function getAuthToken(): string | null {
  const session = getSession()
  return session?.token.token || null
}

/**
 * Get time until token expires
 */
export function getTimeUntilExpiry(): number | null {
  const session = getSession()
  if (!session) return null
  
  return Math.max(0, session.token.expiresAt - Date.now())
}

/**
 * Check if token will expire soon (within 30 minutes)
 */
export function shouldRefreshToken(): boolean {
  const timeLeft = getTimeUntilExpiry()
  if (timeLeft === null) return false
  
  const thirtyMinutes = 30 * 60 * 1000
  return timeLeft < thirtyMinutes
}

/**
 * Refresh token (in production, call backend API)
 */
export async function refreshToken(): Promise<AuthToken | null> {
  const session = getSession()
  if (!session) return null
  
  // TODO: In production, call backend API to refresh token
  // const response = await fetch('/api/auth/refresh', {
  //   method: 'POST',
  //   headers: { 'Authorization': `Bearer ${session.token.token}` }
  // })
  // const data = await response.json()
  // return data.token
  
  // For now, generate a new token client-side
  const newToken = generateToken(session.user)
  storeSession(session.user, newToken)
  return newToken
}

/**
 * Check permission
 */
export function hasPermission(permission: string): boolean {
  const user = getCurrentUser()
  if (!user) return false
  
  // Admin has all permissions
  if (user.permissions.includes('all')) return true
  
  return user.permissions.includes(permission)
}

/**
 * Check role
 */
export function hasRole(role: string): boolean {
  const user = getCurrentUser()
  if (!user) return false
  
  return user.role === role
}

/**
 * Get authorization header for API calls
 */
export function getAuthorizationHeader(): { Authorization: string } | {} {
  const token = getAuthToken()
  if (!token) return {}
  
  return {
    Authorization: `Bearer ${token}`
  }
}

/**
 * Logout helper
 */
export function logout(): void {
  clearSession()
  
  // TODO: Call backend to invalidate token
  // fetch('/api/auth/logout', {
  //   method: 'POST',
  //   headers: getAuthorizationHeader()
  // })
}

/**
 * Session monitor - checks token expiry periodically
 * Call this in your root component
 */
export function startSessionMonitor(onExpiry: () => void): () => void {
  const interval = setInterval(() => {
    if (!isSessionValid()) {
      onExpiry()
    } else if (shouldRefreshToken()) {
      refreshToken().catch(console.error)
    }
  }, 60000) // Check every minute
  
  // Return cleanup function
  return () => clearInterval(interval)
}

